GGML MPT-7B Implementation for CPU Inference
OpenAdaptAI/OpenAdapt pull request #303
Opened 2023-06-21 16:39 UTC by FFFiend

**What kind of change does this PR introduce?**
Addresses #141 
Adds a Replay Strategy that uses the GGML MPT-7B (with 4-bit quantization) model to generate Action completions through inference on the CPU.

**Summary**
Previous MPT-7B implementation required 12+ GB of VRAM and as such was impossible to load on MacOS. This PR resolves that issue and model download + inference can be ran on CPU, provided sufficient memory is available.

**Checklist**
* [x] My code follows the style guidelines of OpenAdapt
* [x] I have perfomed a self-review of my code
* [x] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)

**How can your code be run and tested?**
Well, mixins aren't meant to be run directly, however instructions and further information can be found at #291

2023-06-23 01:30 UTC, KrishPatel13 commented on requirements.txt
> +ctransformers
It will be great if we put this at its alphabetical place when it comes to ordering in requirements :)

2023-06-23 01:33 UTC, KrishPatel13 commented on openadapt/strategies/mixins/mpt7b.py
> +from openadapt.models import Recording
```
from ctransformers import AutoModelForCausalLM
from openadapt.models import Recording
from openadapt.strategies.base import BaseReplayStrategy
```

Reference: https://github.com/MLDSAI/OpenAdapt/pull/306#discussion_r1239163590

2023-06-26 18:39 UTC, FFFiend commented
I see that the ```active_screenshot``` param in the ```get_next_action_event``` method is unused. Did it just end up not being necessary ?

2023-07-04 18:18 UTC, abrichr requested changes
Thanks @FFFiend ! Can you please add a smoke test at the very minimum?

2023-07-04 18:18 UTC, abrichr commented on openadapt/strategies/mixins/mpt7b.py
> +        model_file=self.model_file)
Please format with black. Also please define a constant at the top of the file:

```
MODEL_TYPE = "mpt"
```

Please use double-quotes 🙏

2023-07-04 18:18 UTC, abrichr commented on openadapt/strategies/mixins/mpt7b.py
> +        self.model_file = 'mpt-7b.ggmlv3.q4_0.bin'
Please define constants at the top of the file, and pass in as default arguments here, e.g.:

```
    def __init__(
        self,
        recording: Recording,
        model_path: str = MODEL_PATH,
        model_file: str = MODEL_FILE,
    ):
    ...
    self.model_path = model_path
    self.model_file = model_file
```

2026-01-17 03:25 UTC, abrichr commented
Closing as part of the architecture transition. The legacy codebase has been moved to `legacy/` and frozen at v0.46.0.

If this change is still needed, please:
1. Open a PR against the relevant modular package repository
2. Or re-open this PR targeting the `legacy/` directory if it's a critical legacy fix

See PR #960 for details on the new meta-package architecture.

2026-01-17 03:25 UTC, closed without merging